In [1]:
!pip3 install opencv-python

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
import tensorflow as tf

/Users/pravinpb/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
mnist = tf.keras.datasets.mnist

In [5]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


In [6]:
train_images, test_images = train_images / 255.0, test_images / 255.0


In [7]:
train_images = train_images.reshape((train_images.shape[0], 28 * 28))
test_images = test_images.reshape((test_images.shape[0], 28 * 28))

In [8]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [9]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(28 * 28,)),
    Dense(10, activation='softmax')
])

/Users/pravinpb/Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
model.fit(train_images, train_labels, epochs=10, batch_size=32)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 902us/step - accuracy: 0.8763 - loss: 0.4359
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 861us/step - accuracy: 0.9627 - loss: 0.1257
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 824us/step - accuracy: 0.9765 - loss: 0.0807
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 909us/step - accuracy: 0.9831 - loss: 0.0567
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 913us/step - accuracy: 0.9870 - loss: 0.0424
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 968us/step - accuracy: 0.9887 - loss: 0.0356
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 820us/step - accuracy: 0.9925 - loss: 0.0258
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 849us/step - accuracy: 0.9934 - loss: 0.0220
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 832us/step - accuracy: 0.9948 - loss: 0.0165
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 895us/step - accuracy: 0.9959 - loss: 0.0139


In [12]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc}')

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.9744 - loss: 0.0967
Test accuracy: 0.9775000214576721


In [13]:
import cv2

In [14]:
def extract_frames(video_path, num_frames=300):
    cap = cv2.VideoCapture(video_path)
    frames = []
    for _ in range(num_frames):
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.resize(frame, (28, 28))
        frame = frame.astype('float32') / 255
        frames.append(frame)
    return np.array(frames)

In [15]:
frames = extract_frames('/Users/pravinpb/pycode/openCV/workshop/assets/MNIST Dream video.mp4',100)
print(frames.shape)

(100, 28, 28, 3)


In [16]:
num_classes = 10 
frame_shape = frames[0].shape
num_features = frame_shape[0] * frame_shape[1]

In [17]:
X = frames.reshape(-1, num_features)

In [18]:
X.shape

(300, 784)

In [19]:
predictions = model.predict(X)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [20]:
digit_labels = np.argmax(predictions, axis=-1)

In [21]:
for i, label in enumerate(digit_labels):
    print(f"Frame {i+1}: {label}")

Frame 1: 7
Frame 2: 5
Frame 3: 5
Frame 4: 7
Frame 5: 5
Frame 6: 5
Frame 7: 7
Frame 8: 5
Frame 9: 5
Frame 10: 7
Frame 11: 5
Frame 12: 5
Frame 13: 7
Frame 14: 5
Frame 15: 5
Frame 16: 7
Frame 17: 5
Frame 18: 5
Frame 19: 7
Frame 20: 5
Frame 21: 5
Frame 22: 7
Frame 23: 5
Frame 24: 5
Frame 25: 7
Frame 26: 5
Frame 27: 5
Frame 28: 7
Frame 29: 5
Frame 30: 5
Frame 31: 7
Frame 32: 5
Frame 33: 5
Frame 34: 7
Frame 35: 5
Frame 36: 5
Frame 37: 7
Frame 38: 5
Frame 39: 5
Frame 40: 7
Frame 41: 5
Frame 42: 5
Frame 43: 7
Frame 44: 5
Frame 45: 7
Frame 46: 7
Frame 47: 5
Frame 48: 7
Frame 49: 7
Frame 50: 5
Frame 51: 5
Frame 52: 7
Frame 53: 5
Frame 54: 5
Frame 55: 7
Frame 56: 5
Frame 57: 5
Frame 58: 7
Frame 59: 5
Frame 60: 5
Frame 61: 7
Frame 62: 5
Frame 63: 5
Frame 64: 7
Frame 65: 5
Frame 66: 5
Frame 67: 7
Frame 68: 5
Frame 69: 5
Frame 70: 7
Frame 71: 5
Frame 72: 5
Frame 73: 7
Frame 74: 5
Frame 75: 5
Frame 76: 7
Frame 77: 5
Frame 78: 5
Frame 79: 7
Frame 80: 5
Frame 81: 5
Frame 82: 7
Frame 83: 5
Frame 84: 5
F

Video


In [22]:
def process_frame(frame):
    frame = cv2.resize(frame, (28, 28))
    frame = frame.astype('float32') / 255
    frame = frame.reshape(-1, num_features)
    print(frame)
    prediction = model.predict(frame)
    digit = np.argmax(prediction)
    print(digit)
    return digit

In [23]:
cap = cv2.VideoCapture('/Users/pravinpb/pycode/openCV/workshop/assets/MNIST Dream video.mp4')

while True:
    ret, frame = cap.read()
    print(frame.shape)
    
    if not ret:
        break
    digit = process_frame(frame)
    cv2.putText(frame, str(digit), (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
    cv2.imshow('Frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()


(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.01176471 0.01176471 0.00784314]
 [0.00784314 0.00784314 0.00784314 ... 0.654902   0.03137255 0.03137255]
 [0.03137255 0.         0.         ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
7
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.00784314 0.00784314 0.00784314]
 [0.00784314 0.00784314 0.00784314 ... 0.6509804  0.03137255 0.03137255]
 [0.03137255 0.         0.         ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
7
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.01960784 0.01960784 0.00784314]
 [0.00784314 0.00784314 0.00784314 ... 0.50980395 0.03137255 0.03137255]
 [0.03137255 0.         0.         ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
7
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.22352941 0.22352941 0.00784314]
 [0.00784314 0.00784314 0.00784314 ... 0.3647059  0.00784314 0.00784314]
 [0.007843

2024-05-13 17:54:18.182 Python[2736:85449] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.


15
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.98039216 0.98039216 0.11764706]
 [0.11764706 0.11764706 0.00784314 ... 0.12941177 0.00392157 0.00392157]
 [0.00392157 0.         0.         ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
15
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.9882353  0.9882353  0.84705883]
 [0.84705883 0.84705883 0.00784314 ... 0.06666667 0.         0.        ]
 [0.         0.00392157 0.00392157 ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
25
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.9882353  0.9882353  0.9647059 ]
 [0.9647059  0.9647059  0.12941177 ... 0.02745098 0.         0.        ]
 [0.         0.00784314 0.00784314 ... 0.9882353  0.9882353  0.9882353 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
25
(1080, 1080, 3)
[[0.9882353  0.9882353  0.9882353  ... 0.9882353  0.9882353  0.9882353 ]
 [0.9882353  0.9882353  0.7607843  ... 0.00784314 0.         0.        ]
 [0.

CNN

In [24]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [25]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [26]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [27]:
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

In [28]:
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [29]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.Adadelta(),
              metrics=['accuracy'])

/Users/pravinpb/Library/Python/3.9/lib/python/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [31]:
model.fit(x_train, y_train,
          batch_size=128,
          epochs=20,
          verbose=1,
          validation_data=(x_test, y_test))

Epoch 1/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - accuracy: 0.4944 - loss: 1.9320 - val_accuracy: 0.6863 - val_loss: 1.8498
Epoch 2/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 22ms/step - accuracy: 0.5155 - loss: 1.8681 - val_accuracy: 0.6986 - val_loss: 1.7784
Epoch 3/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - accuracy: 0.5305 - loss: 1.8097 - val_accuracy: 0.7121 - val_loss: 1.7035
Epoch 4/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 24ms/step - accuracy: 0.5419 - loss: 1.7459 - val_accuracy: 0.7262 - val_loss: 1.6256
Epoch 5/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.5569 - loss: 1.6761 - val_accuracy: 0.7378 - val_loss: 1.5462
Epoch 6/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - accuracy: 0.5756 - loss: 1.6068 - val_accuracy: 0.7493 - val_loss: 1.4679
Epoch 7/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.5851 - loss: 1.5393 - val_accuracy: 0.7586 - val_loss: 1.3909
Epoch 8/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 11s 23ms/step - accuracy: 0.5956 - loss: 1.4811 - 

In [32]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.7481516003608704
Test accuracy: 0.8395000100135803


In [38]:
def process_frame(frame):
    # Convert the frame to grayscale
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # Resize the frame to the expected input size of the model
    frame = cv2.resize(frame, (28, 28))  # Adjust size according to your model's input
    
    # Normalize the frame
    frame = frame.astype('float32') / 255
    
    # Expand dimensions to match the model's input shape
    frame = np.expand_dims(frame, axis=0)
    
    # Perform classification
    prediction = model.predict(frame)
    
    # Get the predicted class
    predicted_class = np.argmax(prediction)
    
    return predicted_class

In [41]:
# Open the video file
cap = cv2.VideoCapture('/Users/pravinpb/pycode/openCV/workshop/assets/MNIST Dream video.mp4')

while True:
    # Read the next frame from the video
    ret, frame = cap.read()
    
    if not ret:
        break  # Exit the loop if the frame is empty
    
    # Process the frame
    predicted_class = process_frame(frame)
    
    # Display the frame with the prediction
    cv2.putText(frame, f'Predicted Class: {predicted_class}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    
    # Display the frame
    cv2.imshow('Frame', frame)
    
    # Break the loop on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture object and close windows
cap.release()
cv2.destroyAllWindows()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


2024-05-10 12:20:35.545 Python[56539:432366] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━